### ISSUE TITLE
CSS Bug In Add Comment Form

### ISSUE THREAD

**Issue by fundamental** [llyt/mim#1]
I saw your post on a comment system, but it looks like there's a rendering bug in the css for the add comment form (which I think is in this repo). In firefox 38.2.0 it renders as
![current-form](https://cloud.githubusercontent.com/assets/766621/11595704/d83c609e-9a7e-11e5-9e2e-c8e08e9cbf7c.png)

Using the inspector and injecting a single &nbsp it was possible to perturb this to 
![intended-form](https://cloud.githubusercontent.com/assets/766621/11595752/02ecdfa8-9a7f-11e5-9531-c6990d7acc5a.png)

which I assume was what you had intended.

**Comment by llyt** [comment]
Ohh, thank you, I'm really grateful for that. I will do something about it.
